version: '3'
services:
  patterns-loan-api:
    build:
      context: .
      dockerfile: Loan.API/Dockerfile
    ports:
      - "10010:8080"
    restart: always
    user: "1001"
    volumes:
      - /var/log/patterns/loan:/app/logs
    depends_on:
      - redis
      - rabbitmq

  patterns-core-api:
    build:
      context: .
      dockerfile: Core.API/Dockerfile
    ports:
      - "9010:8080"
    restart: always
    user: "1001"
    volumes:
      - /var/log/patterns/core:/app/logs
    depends_on:
      - redis
      - rabbitmq  

  patterns-account-api:
    build:
      context: .
      dockerfile: Account.API/Dockerfile
    ports:
      - "11010:8080"
    restart: always
    user: "1001"
    volumes:
      - /var/log/patterns/account:/app/logs
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: always

volumes:
  redis_data:
  rabbitmq_data: 